Zanit-Development/Zanit_FE

- zanit_fe/src/App.tsx
- zanit_fe/src/components/error/Page404.tsx
- zanit_fe/src/components/nav/Nav.tsx
- zanit_fe/src/index.tsx
- zanit_fe/src/layouts/Layout.tsx
- zanit_fe/src/layouts/common/button/Button.tsx
- zanit_fe/src/layouts/common/input/CheckboxTag.tsx
- zanit_fe/src/layouts/common/input/CheckboxTerms.tsx
- zanit_fe/src/layouts/common/input/Input.tsx
- zanit_fe/src/layouts/common/input/setPlaceholder.ts
- zanit_fe/src/layouts/common/logo/Logo.tsx
- zanit_fe/src/layouts/footer/Footer.tsx
- zanit_fe/src/layouts/header/Header.tsx
- zanit_fe/src/libs/apis/axios.ts
- zanit_fe/src/libs/apis/baseUrl.ts
- zanit_fe/src/libs/constants/messages/error.ts
- zanit_fe/src/libs/constants/messages/placeholder.ts
- zanit_fe/src/libs/constants/messages/validation.ts
- zanit_fe/src/libs/constants/regex/regex.ts
<br>
- 폴더 트리랑 초기 파일 업로드입니다.
<br>
- 이슈 내용 #2 확인 부탁드립니당
<br>
- #2 
<br><br>
> #2 chore : 폴더구조 및 초기 파일 세팅

- public/index.html
- src/layouts/Layout.tsx
> chore : 모바일 화면 확인을 위한 메타 태그 추가

- public/index.html
- src/App.tsx
- src/components/error/Page404.tsx
- src/layouts/Layout.tsx
- src/pages/NotFound/NotFound.tsx
- src/style/GlobalStyle.tsx
<br>
- 404 페이지 마크업 및 버튼 기능
<br>
<br>
- #13 
<br><br>
> #13 feat : 404페이지

- src/libs/interface/interfaceCommon.tsx
<br>
- 버튼 인터페이스 온클릭 이벤트 추가
<br>
- 
<br>
- #8 
<br><br>
> feat : 버튼 인터페이스 온클릭이벤트 추가

- src/components/error/Page404.tsx
- src/libs/interface/interfaceCommon.tsx
<br>
- 인터페이스 수정사항 반영했습니다~
<br>
-
<br>
- #13 
<br><br>
> #13 fix : interface 반영

- src/assets/images.d.ts
- src/components/common/item/Item.tsx
- src/libs/interface/interfaceCommon.tsx
- src/libs/interface/typeCommon.tsx
- src/pages/search/Search.tsx
- src/style/GlobalStyle.tsx
- tsconfig.json
<br>
- 목록 아이템 컴포넌트 추가
- 아이템 관련 인터페이스, 타입 추가
- 검색 결과 표시부 추가
- li 리스트스타일 초기화
- 타입스크립트 이미지 사용 설정
<br>
- 아이템 사용법
```ts
const itemOptions: ItemProps = {
typeVariants: "primary",
link: "#",
url: sampleImg,
name: "임시",
};
<Item {...itemOptions} />
```
<br>
- #19 #15 
<br><br>
> feat : 목록 아이템 컴포넌트, 검색 결과표시 기능, 스타일 수정사항

- src/libs/constants/options/options.ts
- src/pages/Home.tsx
- src/pages/sign/SignIn.tsx
- src/pages/sign/SignUp.tsx
<br>
- 옵션 공통 사용을 위해 lib폴더 내 constants 폴더로 이동하였습니다.
<br>
- 이 후 옵션에 관련된 값들을 이곳에 추가하여 사용하시면 될것같습니다.
<br>
- #30 
<br><br>
> chore : options 이동 및 적용

- src/components/coupon/HasCoupon.tsx
- src/components/coupon/NotCoupon.tsx
- src/libs/constants/options/options.ts
- src/pages/myCoupon/HowToUse.tsx
<br>
- 버튼 옵션 수정 및 추가
-
<br>
-
<br>
- #32 
<br><br>
> fix : 쿠폰 페이지 버튼 옵션 변경

- src/components/common/alert/Alert.tsx
- src/pages/subscribe/Subscribe.tsx
<br>
- 불필요한 백틱 삭제 및 레이아웃 적용
<br>
-없습니당
<br>
- #33 
<br><br>
> style : 불필요 백틱 삭제, 레이아웃 적용

- src/App.tsx
- src/components/bardetail/BardetailTag.tsx
- src/components/bardetail/Cocktail.tsx
- src/components/tag/Tag.tsx
- src/libs/interface/interfaceBarDetail.ts
- src/libs/utils/Bardetaildummy.ts
- src/libs/utils/Homedummy.ts
- src/pages/bar_detail/Bardetail.tsx
- src/pages/home/Home.tsx
<br>
- 페이지 마크업 했습니다
- 버튼 누르면 쿠폰함으로 갑니다
<br>
- 배포페이지에는 가게 이미지가 여러개 들어가던데 저는 피그마대로 구현했습니다
<br>
- #42 
<br><br>
> #42 feat : 바 상세페이지

- src/libs/constants/options/options.ts
- src/libs/interface/interfaceBarDetail.ts
- src/libs/interface/interfaceCommon.tsx
- src/pages/search/Search.tsx
<br>
- 카멜케이스 소문자로 수정
<br>
-
<br>
- #51 
<br><br>
> fix : 인터페이스 옵션 카멜케이스 소문자로 변경

- src/components/modal/Modal.tsx
<br>
- 카멜케이스 소문자로 변경
<br>
-
<br>
- #52  
<br><br>
> fix : 모달 카멜케이스 소문자로 변경

- src/App.tsx
- src/components/common/button/Button.tsx
- src/components/common/input/Input.tsx
- src/libs/constants/options/options.ts
- src/libs/constants/values/outputValues.ts
- src/libs/constants/values/placeholder.ts
- src/pages/sign/PasswordFind.tsx
- src/pages/sign/PasswordReset.tsx
- src/pages/sign/SignIn.tsx
<br>
- 비밀번호 찾기 페이지 UI
- 비밀번호 재설정 페이지 UI
<br>
- 
<br>
- #23 
<br><br>
> design : 비밀번호 찾기, 재설정 페이지

- src/layouts/nav/Nav.tsx
<br>
- 페이지 별 nav 버튼 활성화 연결
-
<br>
- 이후 페이지 추가 되는거 있으면 알려주세요~
- 사실 배열에 맞는 path 넣어주기만 하면 되긴 함 (해달라는 뜻은 아니고 그냥 그렇다구요ㅋㅎ) 
<br>
- #6 
<br><br>
> desgin : 페이지 별 nav 버튼 활성화 연결

- src/libs/constants/options/options.ts
- src/libs/constants/values/outputValues.ts
- src/pages/subscribe/Subscribe.tsx
- src/pages/subscribe/SubscribeInfo.tsx
- src/pages/subscribe/subscribeOption.ts
<br>
- 구독페이지 변경사항 적용
<br>
-
<br>
- #57 
<br><br>
> design : 구독페이지 변경사항 적용

- src/components/home/HomeBanner.tsx
- src/libs/utils/Homedummy.ts
- src/pages/home/Home.tsx
<br>
- prop 이름 변경에 따른 오류 수정입니다
<br>
-
<br>
-  #21 
<br><br>
> (#21) fix : 오류 수정

- src/components/common/item/Item.tsx
- src/components/tag/Tag.tsx
- src/pages/search/Search.tsx
<br>
- 카멜케이스 소문자로 수정
- 라디오버튼 재선택시 체크해제되도록 변경
<br>
-
<br>
- #51 
<br><br>
> fix : 카멜케이스 소문자로 수정, 태그 라디오버튼 수정

- src/components/common/input/setPlaceholder.ts
- src/components/coupon/AutoPaymentCoupon.tsx
- src/components/coupon/HasCoupon.tsx
- src/components/coupon/ManualPaymentCoupon.tsx
- src/components/error/Page404.tsx
- src/libs/constants/options/options.ts
- src/libs/constants/values/placeholder.ts
- src/pages/sign/SignUp.tsx
- src/pages/subscribe/subscribeOption.ts
<br>
-
-
<br>
-
<br>
- 
<br><br>
> Fix : 페이지 에러 해결

- src/layouts/Layout.tsx
- src/layouts/header/Header.tsx
- src/layouts/nav/Nav.tsx
- src/pages/subscribe/Subscribe.tsx
<br>
- nav에 의견 보내기 추가되었습니다.
- header 상단 고정 해놨습니다.
- 애플리케이션 전체 100vh로 지정하여 앱 내에서 스크롤바 가능하도록 구현했습니다.
<br>
- 구독하기 페이지 이미지 넘쳐서 가로 스크롤바 생기는 문제 있어서 width 100% 처리 해뒀어요! (전의 코드 주석 처리 되어 있습니다)
- 스크롤바 디자인 추천 받아요
<br>
- #6 
<br><br>
> design : header 고정, main 스크롤바

- src/pages/subscribe/Subscribe.tsx
<br>
- 구독 페이지 상단 여백 길이조절
<br>
-
<br>
- 
<br><br>
> design : 상단여백 길이조절

- src/components/common/input/CheckboxTag.tsx
- src/components/common/input/CheckboxTerms.tsx
- src/components/common/select/Select.tsx
- src/pages/admin/bar/BarManagement.tsx
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/ManageInfoOptions.ts
- src/pages/admin/bar/ManageOrder.tsx
<br>
- 바 정보, 주문 관리 페이지
<br>
-
<br>
- #74 
<br><br>
> feat : 어드민 바 관리 페이지

- package-lock.json
- package.json
- src/App.tsx
<br>
- 깃허브 페이지 배포 테스트를 위한 gh-pages 모듈 설치, 셋팅
<br>
[확인](https://github.com/Zanit-Development/Zanit-Preview/blob/main/README.md)
<br>
- 
<br><br>
> feat : gh-pages 배포 테스트

- src/libs/apis/axios.ts
- src/libs/apis/user.ts
- src/pages/sign/SignIn.tsx
<br>
- 폼데이터 인스턴스 추가되었어요
<br>
- 로그인 폼데이터 값은 제대로 들어가는데 302에러, CORS 뜨는중~
<br>
- #23 
<br><br>
> feat : 로그인 기능 및 폼 데이터 인스턴스 추가

- src/components/common/input/Input.tsx
- src/pages/admin/bar/BarManagement.tsx
- src/pages/admin/bar/ManageInfo.tsx
<br>
- 관리자 페이지 바 관리 상단 스타일 적용
<br>
-
<br>
- #74 
<br><br>
> design : admin 바 관리 페이지

- src/pages/admin/bar/BarManagement.tsx
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/ManageInfoOptions.ts
- src/pages/admin/bar/handler.ts
<br>
- 정보 관리페이지 중부
- 핸들러 분리
<br>
-
<br>
- #74 
<br><br>
> feat : 어드민 정보관리

- src/components/modal/UseSignPage/PopupPasswordFind.tsx
- src/components/modal/UseSignPage/PopupSignUpSuccess.tsx
- src/libs/constants/options/options.ts
- src/libs/constants/values/outputValues.ts
- src/pages/sign/PasswordFind.tsx
<br>
<br>
-
<br>
- #23 
<br><br>
> design: 비밀번호 찾기 모달

- src/App.tsx
- src/components/admin/management/CocktailItem.tsx
- src/components/bardetail/BarInfomation.tsx
- src/components/bardetail/Cocktail.tsx
- src/components/common/cocktail/Cocktail.tsx
- src/components/tag/Tag.tsx
- src/components/tag/TagList.tsx
- src/layouts/adminLayout/AdminLayout.tsx
- src/libs/interface/interfaceCommon.tsx
- src/pages/admin/bar/AdminBarDetail.tsx
- src/pages/barDetail/Bardetail.tsx
- src/pages/search/Search.tsx
<br>
- tagid 소문자로 변경
- 상세페이지 마크업
- 칵테일 컴포넌트 위치 변경
<br>
-
<br>
- #91 
<br><br>
> admin bar information 마크업

- src/libs/interface/interfaceCommon.tsx
- src/libs/interface/typeEvent.tsx
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/ManageInfoOptions.ts
- src/pages/admin/bar/handler.ts
<br>
- 숫자 입력부 콤마, 숫자외입력 처리 등
- 핸들러 분리 
<br>
- 한글입력시 지워지는 이슈가 있습니당
<br>
- #74
<br><br>
> feat : 관리자 페이지 관련

- src/App.tsx
- src/components/membership/MembershipType.tsx
- src/libs/interface/interfaceMembership.ts
- src/libs/interface/typeCommon.tsx
- src/pages/subscribe/Subscribe.tsx
- src/pages/subscribe/membership/Membership.tsx
- src/pages/subscribe/membership/handleMembership.ts
- src/pages/subscribe/membership/membershipOption.ts
<br>
- 구독 선택 페이지
- 멤버십 종류 컴포넌트
<br>
-
<br>
- #33 
<br><br>
> feat : 구독 종류 선택페이지

- src/libs/interface/interfaceManagement.ts
- src/pages/admin/bar/ManageOrder.tsx
<br>
- 주문관리 페이지 작업
<br>
-
<br>
- #74 
<br><br>
> feat : 주문 관리

- src/components/common/button/Button.tsx
- src/components/common/input/Input.tsx
- src/components/common/item/Item.tsx
- src/components/coupon/HasCoupon.tsx
- src/components/coupon/ManualPaymentBtn.tsx
- src/components/coupon/NotCoupon.tsx
- src/components/coupon/UseHistory.tsx
- src/components/home/HomeBanner.tsx
- src/components/home/ItemList.tsx
- src/components/membership/MembershipType.tsx
- src/components/modal/Modal.tsx
- src/components/search/Category.tsx
- src/components/stopSubscribe/PopupComplete.tsx
- src/components/stopSubscribe/PopupPromotion.tsx
- src/components/stopSubscribe/StopMembership.tsx
- src/layouts/footer/Footer.tsx
- src/layouts/nav/Nav.tsx
- src/libs/constants/options/options.ts
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/home/Home.tsx
- src/pages/myCoupon/HowToUse.tsx
- src/pages/search/Search.tsx
- src/pages/sign/PasswordFind.tsx
- src/pages/sign/SignIn.tsx
- src/pages/sign/SignUp.tsx
- src/pages/subscribe/membership/Membership.tsx
- src/style/GlobalStyle.tsx
<br>
**본인이 맡은 부분 확인해주세요**
- 스타일조정
<br>
- 내부요소로 마진 잡은거 수정
- 스크롤바 display:none
- 간격 조정
- font-size, font-height, color 조정
- 그 외 크기, 이벤트 등등 조정
<br>
- #100
<br><br>
변경 비교 이미지 (안넣은것도 있음)
https://nostalgic-skate-c18.notion.site/fix-style-3dd441a8b1dc414486ce4338764efc96?pvs=4
> fix : 스타일 조정

- src/components/common/item/Item.tsx
- src/libs/interface/interfaceCocktail.ts
- src/pages/search/Search.tsx
- src/pages/search/handleSubmit.ts
- src/pages/search/initBarList.ts
<br>
- 검색시 검색 칵테일 표시
- 빈값시 전체 칵테일 표시
<br>
- 빈값 또는 바나나, 사과, 귤 검색 가능
<br>
- #111
<br><br>
> feat : 검색기능

- src/components/search/Category.tsx
- src/libs/interface/interfaceCommon.tsx
- src/libs/interface/interfaceSearch.ts
- src/pages/search/Search.tsx
- src/pages/search/handleSubmit.ts
<br>
- 검색 카테고리 설정 별 검색결과 나올수 있도록 만들어놓긴 했는데\
현재 바는 검색이 되지 않는 이슈가 있기 때문에 확인은 못해봤읍니다. ㅠ,ㅠ
<br>
- 진행중
<br>
- #111 
<br><br>
> feat : 검색 기능

- src/components/admin/management/CocktailItem.tsx
- src/pages/admin/bar/ManageInfo.tsx
<br>
- 폼 내부 정보 입력값 사용 가능하도록 수정
- 이미지 추가시 파일, 미리보기 추가, 삭제 기능 추가
<br>
- 백엔드 입력값이랑 피그마상 입력값에 차이가있어서 확인중임다.
내용
<br>
- #74 
<br><br>
> feat : 어드민 바 정보 관리페이지

- src/components/tag/NewTag.tsx
- src/components/tag/SearchTag.tsx
- src/pages/search/Search.tsx
- src/pages/search/handleSubmit.ts
- src/pages/search/initBarList.ts
<br>
- 카테고리별 태그 분리 및 태그 선택시 해당하는 값 필터
- 카테고리 = 칵테일인 경우 초기값 및 태그 옵션, 칵테일 값은 따로 관리
- 칵테일 표시 안되는 현상 수정
<br>
- 필터를 프론트에서 처리하다보니 코드가 많이 길어지고있슴당
<br>
- #111 
<br><br>
> feature : 검색 태그 기능, 칵테일 목록

- src/components/modal/useSignPage/PopupLogout.tsx
- src/layouts/adminLayout/AdminLayout.tsx
- src/layouts/adminLayout/AdminNav.tsx
- src/layouts/nav/Nav.tsx
- src/libs/apis/user.ts
- src/pages/admin/AdminSignIn.tsx
- src/pages/sign/SignIn.tsx
<br>
- admin 레이아웃 nav 분리
- admin 로그아웃 nav에 추가
- 로그아웃 popup 생성
- 관리자, 유저 로그인 쿠키 문제 로그인 페이지로 가면 쿠키 사라지게 해뒀어요
<br>
- 또 다른 버그 생기면 바로 말씀해주십셔,,,
<br>
- #23 
<br><br>
> fix: 로그인 오류 수정

- src/pages/search/Search.tsx
- src/pages/search/handleSubmit.ts
<br>
- 칵테일 카테고리 선택 후 검색시 바 이름으로 검색되도록 변경
- 칵테일 태그 입문자용, 캐주얼드링커용, 헤비드링커용 세가지로 변경
<br>
- 검색 기능은 이렇게 마감하고 이후 페이징 추가되면 페이징만 추가하는걸로 하는게 좋을것같슴다
<br>
- #111 
<br><br>
> refactor : 칵테일검색 바이름검색으로 변경 및 칵테일 태그 recoUser에 맞춰서 변경

- src/components/barDetail/BarInfomation.tsx
- src/components/tag/Tag.tsx
- src/components/tag/TagList.tsx
- src/libs/interface/interfaceCommon.tsx
- src/pages/home/Home.tsx
<br>
-
-
<br>
-
<br>
- #114 
<br><br>
> (#114) add : home->search

- src/libs/func/generator.ts
- src/pages/search/Search.tsx
- src/pages/search/options.ts
<br>
- 태그 랜덤 생성기입니당
- 파라미터 값으로 생성할 태그 개수 넣으시면 됩니다.
- 태그 개수보다 파라미터 값이 높으면 에러 띄웁니다용.
- 기능은 바 분위기, 바 위치, 둘 다 이렇게 세 가지입니다.
<br>
- 랜덤생성기로 생성된 태그를 상태로 관리해서 홈이랑 공용으로 사용하면 좋을것같습니당
- 문제있으면말씀해주세용
```ts
const 바전체태그랜덤 = generator.randomAllTag(8); // 위치 + 분위기
const 바위치태그랜덤 = generator.randomLocationTag(8);
const 바분위기태그랜덤 = generator.randomMoodTag(8);
```
<br>
- #111 
<br><br>
> feat : 태그 랜덤 생성기

- src/components/search/Category.tsx
- src/libs/func/generator.ts
- src/libs/interface/interfaceCommon.tsx
- src/pages/search/Search.tsx
<br>
- 홈에서 검색으로 넘어올 경우 검색결과가 제대로 표시됩니다. (바 이름으로만 검색 가능)
- 홈에서 태그 선택으로 넘어올 경우 해당 카테고리, 태그가 선택되어있도록 수정
<br>
-
<br>
- #111 
<br><br>
> fix : 홈 -> 검색으로 카테고리, 태그, 검색으로 넘어오는 경우 해당 값이 제대로 적용되지 않는 현상 수정

- src/components/common/input/Input.tsx
- src/components/sign/SignUpForm.tsx
- src/libs/interface/interfaceCommon.tsx
<br>
- 애니메이션 처리 넣었슴다
- authError 에 따라 전화번호칸 disabled 넣었어요
<br>
- authButtonAnimationInProgress : 깜빡이는 애니메이션 진행하는 동안엔 이벤트 안되게 막는 역할을 해요
- 추후에 api 될때 authError 이용해서 작업하면 될거같긴 합니다
- input 컴포넌트, disabled 일땐 hover 안뜨게 바깟어요
<br>
- 
<br><br>
> add : signup 애니메이션 처리

- src/components/sign/SignInForm.tsx
- src/pages/sign/PasswordReset.tsx
<br>
- 맥 OS 에서 input에 한글 입력 들어가는 경우와 전화번호, 비밀번호 불일치 시 서버 응답 500 뜨면 안내 문구 뜨게 바꿔뒀습니다. (쟁님 이거 테스트 한번만 해주세요 ㅋㅋ ㅜㅜ)
- test 메서드 관련 유효성 문제가 고쳐졌습니다.
<br>
-
<br>
- #23
<br><br>
> fix: 로그인 관련 유효성 및 버그 수정

- src/App.tsx
- src/layouts/Layout.tsx
- src/layouts/adminLayout/AdminLayout.tsx
<br>
-
-
<br>
- 모바일 환경에서 height이 브라우저 상,하단 바에 가려지는 문제가 생겨서 수정했습니다
<br>
- 
<br><br>
> design : height 조정

- src/components/barDetail/BarInfomation.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> design : fontsize 조정

- src/components/sign/SignInForm.tsx
- src/libs/constants/options/options.ts
- src/libs/interface/interfaceCommon.tsx
<br>
<br>
- 
<br>
- #23 
<br><br>
> feat: 비밀번호 보기 추가

- src/App.tsx
- src/components/home/HomeBanner.tsx
- src/components/tag/Tag.tsx
- src/layouts/Layout.tsx
- src/pages/home/Home.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> 홈, 레이아웃 변경

- src/components/admin/management/handleCocktailItem.ts
- src/libs/interface/interfaceCommon.tsx
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/ManageInfoOptions.ts
- src/pages/admin/bar/Popup.tsx
- src/pages/admin/bar/handler.ts
- src/pages/search/Tag.tsx
<br>
- 바정보관리 페이지, 팝업 페이지 input, textarea등 값 입력시 렌더링간섭 안되도록 수정
- 태그 수정 이후 팝업 제대로 동작하지 않는 현상 수정
<br>
- 
<br>
- #74 
<br><br>
> refactor : 바정보관리, 팝업 input 값 변경시 리렌더링 되지 않도록 수정, 팝업 오류 수정

- src/pages/search/SearchList.tsx
- src/pages/search/Tag.tsx
<br>
- 제목과같숨다
-
<br>
-
<br>
- #111 
<br><br>
> refactor : 바, 칵테일 요청 병렬처리, fix : 태그 선택된 상태에서 다른 태그 선택시 이전 선택태그 다시 나타나지 않는 현상 수정

- public/_redirects
- src/layouts/adminLayout/AdminLayout.tsx
- src/pages/admin/AdminSignIn.tsx
- src/setupProxy.js
<br>
-
-
<br>
- admin login 디자인 수정
- admin layout 100vh -> 100dvh
<br>
- 
<br><br>
> design 수정 및 api url 변경

- public/_redirects
- src/setupProxy.js
<br>
-
-
<br>
-
<br>
- 
<br><br>
> chore : backend url 변경

- public/_redirects
- src/App.tsx
- src/components/sign/SignUpForm.tsx
- src/libs/apis/axios.ts
- src/setupProxy.js
<br>
- 가은 : 버튼타입 수정
- 재영 : 404 처리 + axios
<br>
-
<br>
- #27 
<br><br>
> (#27) fix: test 메서드 수정 및 button type 변경

- src/pages/search/SearchForm.tsx
- src/pages/search/SearchList.tsx
- src/pages/subscribe/membership/Membership.tsx
- src/pages/subscribe/membership/handleMembership.ts
<br>
- 이미지 경로 변경
-
<br>
-
<br>
- #111 
<br><br>
> fix : 검색결과 이미지 패스 변경

- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/Popup.tsx
- src/pages/admin/bar/RegistBarImageList.tsx
- src/pages/admin/bar/RegistCocktailList.tsx
- src/recoil/barManageAtom.ts
<br>
- 바 관리 페이지 칵테일 등록, 바 이미지 등록 컴포넌트 분리
- 리렌더링 최소화
<br>
-
<br>
- #74 
<br><br>
> refactor : 바관리페이지 컴포넌트분리, 리렌더최소화

- src/App.tsx
- src/components/sign/SignInForm.tsx
- src/components/stopSubscribe/StopMembership.tsx
- src/pages/Temporary.tsx
<br>
**- "/" : home**
**- "/portal" : 이전에 있던 링크들 모아놓은 페이지**
<br>
- 변경사항 꼭 확인해주세욥
<br>
- 
<br><br>
> 라우터 수정 !! (홈 : "/", 링크 모아놓은 페이지 url : "/portal" 로 변경)

- src/App.tsx
- src/components/sign/SignInForm.tsx
- src/components/stopSubscribe/StopMembership.tsx
- src/pages/Temporary.tsx
- src/pages/search/SearchList.tsx
- src/pages/subscribe/membership/Membership.tsx
<br>
- 검색 이미지 없을 경우 에러 발생 방지
- 붙페 링크 반대로 설정 수정
<br>
-
<br>
- #111 
<br><br>
> fix : 부트페이 링크 반대로 설정됨 수정, 검색 이미지가 없는 경우 에러 방지(바로 엎+머지 부탁용)

- src/layouts/footer/Footer.tsx
<br>
- 푸터 디자인 변경
-
<br>
<br>
- 
<br><br>
> design : footer 수정

- src/layouts/footer/Footer.tsx
- src/pages/subscribe/membership/Membership.tsx
<br>
- 푸터 수정
-
<br>
- 없슴다
<br>
- 
<br><br>
> 배포 업데이트 - 3

- src/components/home/HomeBanner.tsx
- src/libs/apis/user.ts
- src/libs/interface/interfaceAPI.ts
- src/pages/barDetail/Bardetail.tsx
- src/pages/subscribe/Subscribe.tsx
- src/pages/subscribe/membership/Membership.tsx
<br>
- home banner navigate처리
- userInfo interface 처리
<br>
- filechange 확인해주세욤
<br>
- #114 
<br><br>
> refactor : banner navigate 분기처리 및 user interface

- src/components/sign/SignUpForm.tsx
<br>
- 회원가입 인증해야되는거 풀어뒀어욤
-
<br>
-
<br>
- 
<br><br>
> test: 회원가입 인증 해제

- src/components/sign/SignInForm.tsx
- src/libs/apis/user.ts
- src/pages/sign/PasswordFind.tsx
- src/pages/sign/PasswordReset.tsx
<br>
- 이후 작업은 말씀 나눠봐야 할 것 같아요
- 500 에러 발생 중임니다
<br>
- 비밀번호 재설정에 전화번호 들어가서 userInfo 불러오는건데 다 불러오는게 맞나요,,, 전화번호만 불러오면 될 거 같기도 한대,,, 긴가민가 
<br>
- #23 
<br><br>
> feat: 비밀번호 찾기, 재설정 코드 수정

- src/components/admin/management/CocktailItem.tsx
- src/components/admin/management/handleCocktailItem.ts
- src/libs/interface/interfaceCocktail.ts
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/Popup.tsx
- src/pages/admin/bar/RegistCocktailList.tsx
<br>
- 백단 디비 속성에 맞게 속성명 변경
- 칵테일 목록에 표시하는 기능(체크박스에 따라 값 변경 되도록 적용)
<br>
-
<br>
- #74 
<br><br>
> feat : 칵테일 표시기능 속성값에 적용

- src/libs/apis/axios.ts
- src/libs/interface/interfaceCocktail.ts
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/Popup.tsx
<br>
- 바, 칵테일 api 연결해서 바 등록 확인
- DB 속성명에 맞춰서 인터페이스 속성명 변경
<br>
- 현재 칵테일은 등록이안됩니당
<br>
- #74 
<br><br>
> feat : 바,칵테일 등록 api 연결

- src/pages/admin/bar/ManageInfo.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> fix : 바등록 파일업로드 리스트로 수정

- src/components/sign/SignInForm.tsx
- src/layouts/adminLayout/AdminNav.tsx
- src/layouts/nav/Nav.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> fix : lowercase

- src/components/sign/SignInForm.tsx
- src/layouts/adminLayout/AdminNav.tsx
- src/layouts/nav/Nav.tsx
- src/pages/admin/bar/ManageInfo.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> 배포 업데이트 - 7 

- src/App.tsx
- src/components/common/item/Item.tsx
- src/components/coupon/HasCoupon.tsx
- src/components/coupon/ManualPaymentBtn.tsx
- src/components/coupon/UseHistory.tsx
- src/components/home/HomeBanner.tsx
- src/components/home/ItemList.tsx
- src/components/modal/useSignPage/PopupPasswordFind.tsx
- src/components/modal/useSignPage/PopupSignUpSuccess.tsx
- src/components/stopSubscribe/PopupPromotion.tsx
- src/components/useCoupon/UseCouponResultPopup.tsx
- src/layouts/adminLayout/AdminNav.tsx
- src/layouts/nav/Nav.tsx
- src/pages/Temporary.tsx
- src/pages/barDetail/Bardetail.tsx
- src/pages/sign/PasswordResetOk.tsx
- src/pages/sign/SignIn.tsx
- src/pages/sign/SignUp.tsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> design : 홈 화면 이름 버그 수정

- src/pages/admin/bar/Popup.tsx
<br>
- 칵테일 금액 입력부 추가, 입력 기능 추가
-
<br>
- 
<br>
- #74  
<br><br>
> feat : 칵테일 금액입력 기능 추가, 스타일 적용

- src/components/useCoupon/ShowPopupButton.tsx
- src/components/useCoupon/UseCouponPopup.tsx
- src/libs/apis/useCoupon.ts
- src/libs/interface/interfaceUseCoupon.ts
- src/pages/myCoupon/UseCoupon.tsx
<br>
-
-
<br>
-
<br>
- #119
<br><br>
> refactor : coverChargeoff로 변경, useCoupon interface refactor

- src/components/home/HomeBanner.tsx
- src/components/sign/SignInForm.tsx
- src/libs/apis/user.ts
<br>
-
-
<br>
- 로그인이 비밀번호가 틀려도 작동하던 버그가 있었숩니당
<br>
- 
<br><br>
> fix : 로그인 버그 수정

- src/pages/subscribe/membership/Membership.tsx
- src/pages/subscribe/membership/Popup.tsx
<br>
- 기존 구독시작하기에서 유저정보 확인하는 방식에서 구독 페이지로 넘어가면 바로 유저 정보를 받아오는 방식으로 변경
- 이미 구독자인 경우 띄워줄 팝업 추가
- X 구독자인 경우 팝업으로 이미 구독자 알림 팝업
- 구독자인 경우 연장하기, 구독자가 아닌경우 구독하기 분기처리
<br>
-
<br>
- #33 
<br><br>
> Feat : X멤버십 구독자인 경우 '이미구독자'팝업 되는 기능, 팝업, 구독/연장 분기처리

- src/components/barDetail/BarInfomation.tsx
- src/components/home/ItemList.tsx
- src/libs/apis/barDetail.ts
- src/libs/interface/interfaceAPI.ts
- src/libs/interface/interfaceBarDetail.ts
- src/libs/utils/Bardetaildummy.ts
- src/pages/admin/bar/AdminBarDetail.tsx
- src/pages/admin/bar/getAdminBar.ts
<br>
- 바 디테일 변경사항 반영
- 홈화면 기능 수정
<br>
- 구 + 주소 상세 ex) 강남구 + 역삼동 어쩌구
- 홈 아이템 리스트 슬라이드 버튼 조건을 바꿧슴니다
<br>
-  #115
<br><br>
> feat : bar location detail 추가

- src/components/admin/management/CocktailItem.tsx
- src/libs/constants/options/options.ts
- src/libs/constants/values/outputValues.ts
- src/libs/interface/interfaceCocktail.ts
- src/pages/admin/bar/ManageInfo.tsx
- src/pages/admin/bar/ManageInfoOptions.ts
- src/pages/admin/bar/Popup.tsx
- src/pages/admin/bar/RegistCocktailList.tsx
- src/pages/admin/bar/sample.json
- src/recoil/barManageAtom.ts
<br>
- ~칵테일 등록 시도중입니다.~ 성공했습니다
- 등록된 칵테일 수정버튼 클릭시 팝업 및 해당 칵테일 값 자동입력 기능 추가
- 구독 여부에 따라 구독 연장/구독 신청 값 추가
- 폼데이터 name값을 백엔드 코드 name값과 통일 -> 폼데이터에 값을 직접 추가하는 방식에서 폼 자체를 추가하는 방식으로 변경
<br>
- 문서내 TODO, ISSUE 확인하시면 됩니당
- tsconfig 내 target 항목을 'es6' 으로 변경해야 에러가 안납니당!
<br>
- #33 
- #74 
<br><br>
> feat : 관리자 바,칵테일 관련 / 구독 여부 관련 버튼값 등 / refactor : formdata값 직접 넣는 코드 제거 -> name값 통일후 form 자체 입력되도록 수정

- package-lock.json
- package.json
- src/pages/admin/bar/AdminBarDetail.tsx
<br>
-
-
<br>
- 없슴니다
<br>
- 
<br><br>
> fix : 오타 수정

- tsconfig.json
<br>
-
-
<br>
- target값 es5 -> ES2015
<br>
- 
<br><br>
> fix : tsconfig target 변경
